### ISSUE TITLE
[Documentation] Cannot connect to an anonymous registry.

### ISSUE THREAD

**Issue by johnsudaar** [deitch/docker_registry2#1]
Hello,

Thanks for making this gem.
I don't know if i'm not using the gem correctly or if there is a error with your documentation.
But the line :
```ruby
reg = DockerRegistry.new("https://my.registy.corp.com")
```
Do not work. (`undefined method 'new' for DockerRegistry:Module`)

I must use :
```ruby
reg = DockerRegistry::Registry.new("https://my.registry.corp.com")
```

**Comment by deitch** [comment]
Yes, how strange. I have no idea why I mistyped it. I created a convenience function `DockerRegistry.connect(url)`. I am fixing it now.
