### ISSUE TITLE
Disparity in URL via curl with no authentication for search

### ISSUE THREAD

**Issue by indykish** [deitch/docker_registry2#5]
Hi,

My objective is to implement search of "public/private docker images when the user types
`wor` - we list `wordpress` in our UI.

I tried searching an image `wordpress` from dockerregistry.

Here  is my code.

```ruby
require 'docker_registry2'
require 'rest-client'

reg = DockerRegistry.connect("https://registry.hub.docker.com")
puts "----"
puts reg.inspect

results = reg.search("wordpress")
puts results.inspect
```
I received an error  by adding debug to it, and in crux found that `rest_client` tries to look for 
`https://registry.hub.docker.com/v2/_catalogs`. It ain't there with no auth.

```
[ram@ramwork:Desktop]$ ruby 1.rb
------- 
"get"
"/v2/"
"https://registry.hub.docker.com:443"
https://registry.hub.docker.com:443/v2/
--------------
=-==== unauthorized
--------------- sending response
<RestClient::Response 200 "{}">
=================================
----
#<DockerRegistry::Registry:0x00000001ccde58 @uri=#<URI::HTTPS https://registry.hub.docker.com>, @base_uri="https://registry.hub.docker.com:443", @user=nil, @password=nil>
------- 
"get"
"/v2/_catalog"
"https://registry.hub.docker.com:443"
https://registry.hub.docker.com:443/v2/_catalog
--------------
/home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response': 404 Not Found (RestClient::NotFound)
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:103:in `return!'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:860:in `process_result'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:776:in `block in transmit'
	from /home/ram/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/docker_registry2-0.3.0/lib/registry/registry.rb:108:in `doreq'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/docker_registry2-0.3.0/lib/registry/registry.rb:20:in `doget'
	from /home/ram/.rvm/gems/ruby-2.3.1/gems/docker_registry2-0.3.0/lib/registry/registry.rb:32:in `search'
	from 1.rb:8:in `<main>'


```

Whereas if i do this curl command i receive the results like charm :)

```curl -s -S 'https://registry.hub.docker.com/v2/repositories/library/centos/' | sort```

Should i fix the url in case of "no auth" ?

**Comment by indykish** [comment]
I tried all the versions, with auth as well, but didn't get through.

Nevermind, i switched to this gem, and it works. https://github.com/rosylilly/docker_registry

``
registry = DockerRegistry::Registry.new("https://registry.hub.docker.com")
puts registry.inspect
aa = registry.search('wordpress')
puts aa.inspect
```

````
$ ruby 1.rb
#<DockerRegistry::Registry:0x00000001990dd0 @uri=#<URI::HTTPS https://registry.hub.docker.com>, @client=#<DockerRegistry::Client:0x00000001990b00 @base_uri="https://registry.hub.docker.com:443", @faraday=#<Faraday::Connection:0x000000019909c0 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00000001990510 @handlers=[FaradayMiddleware::EncodeJson, DockerRegistry::OjParser, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTPS https://registry.hub.docker.com/>, @proxy=nil>>>
[#<DockerRegistry::Repository registry.hub.docker.com/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/appcontainers/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/bitnami/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/centurylink/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/baseboxorg/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/dsifford/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/scjalliance/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/dsteinkopf/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/miqueladell/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/bakudankun/wordpress-ja >, #<DockerRegistry::Repository registry.hub.docker.com/ddaishin/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/ikoptiev/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/maximiliend/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/cuuats/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/kaihofstetter/wordpress-cli >, #<DockerRegistry::Repository registry.hub.docker.com/derjudge/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/devgeniem/alpine-wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/gaoyifan/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/orukami/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/miko2u/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/apsl/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/ianusit/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/davask/d-wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/cloyne/wordpress >, #<DockerRegistry::Repository registry.hub.docker.com/mykmelez/wordpress-pwa >]
```

I am closing this issue. Thanks for the awesome gem though.

**Comment by deitch** [comment]
Hi @indykish 

First, thank you for the compliment and the issue.

I knew of that gem when I put together this one. The problem is that no one supported the registry API v2, except by calling out to a shell to run `docker ___`. That doesn't work without a docker engine installed. Considering that the registry is just a REST API, we should be able to support registry API v2 natively from Ruby. 

Last I checked, v2 doesn't even have a search endpoint. If you check the README, you will see that I essentially implemented it in an inefficient way.
