### ISSUE TITLE
tag pagination does not require `last`

### ISSUE THREAD

**Issue by thepwagner** [deitch/docker_registry2#56]
When listing the tags of https://quay.io/repository/invisionag/yet-another-cloudwatch-exporter?tag=latest&tab=tags , results are limited to the first 50 tags. Minimal example:

```ruby
reg = DockerRegistry2::Registry.new("https://quay.io")
tags = reg.tags("invisionag/yet-another-cloudwatch-exporter", auto_paginate: true)
```

I think that's because the implementation of pagination expects registries to use [a field called `last`](https://github.com/deitch/docker_registry2/blob/220c03d5d2ad0268ca97ecabb16cc8ec58943dbd/lib/registry/registry.rb#L226) to identify the next page, but quay.io is using a different format:
```
$ curl -I https://quay.io/v2/invisionag/yet-another-cloudwatch-exporter/tags/list
HTTP/2 200
server: nginx/1.12.1
date: Fri, 25 Jun 2021 19:30:43 GMT
content-type: application/json
content-length: 730
link: </v2/invisionag/yet-another-cloudwatch-exporter/tags/list?next_page=gAAAAABg1i7jwRsgyD_X_wcMmj11T0waURK8w2MpuKG3a5B5C_iWzc1YMHTRDAPiwnqT4s0gkVdH7tUbc5HlXy7RxT139fZABKiEw7vtjNWj8D8dSAAy-fQ%3D&n=50>; rel="next"
x-frame-options: DENY
strict-transport-security: max-age=63072000; preload
```

If we refer to Docker's implementation, I think the correct strategy is to keep fetching the provided link URL without decoding it. https://github.com/distribution/distribution/blob/a1e30cca34d3ef49514fb22244a1ad375828a24d/registry/client/repository.go#L244-L254
```
$ curl -I https://quay.io/v2/invisionag/yet-another-cloudwatch-exporter/tags/list | grep link
link: </v2/invisionag/yet-another-cloudwatch-exporter/tags/list?next_page=gAAAAABg1i8zYtGx8If7aoSXYvfvVdpc9EQh9q83jkZF8YI8VEQdOd0gZDIiRbK0fJN-GAvWz5uoshowtFRNiP3SIXWpWr9cOhvAZz944fNzgVB5XlEbwec%3D&n=50>; rel="next"

$ curl -I "https://quay.io/v2/invisionag/yet-another-cloudwatch-exporter/tags/list?next_page=gAAAAABg1i8zYtGx8If7aoSXYvfvVdpc9EQh9q83jkZF8YI8VEQdOd0gZDIiRbK0fJN-GAvWz5uoshowtFRNiP3SIXWpWr9cOhvAZz944fNzgVB5XlEbwec%3D&n=50" | grep link
link: </v2/invisionag/yet-another-cloudwatch-exporter/tags/list?next_page=gAAAAABg1i9UjTgAMlBO-fMYc3TNmgMXmn4Y4uZd6SY_bwY3gYK0NCY6N4QtM4YyRSVJITVNODf9K84aLUDZaVXmsHUfXryTblSGiLFb36Y_TY3Yf5sTBtw%3D&n=50>; rel="next"

$ curl -I "https://quay.io/v2/invisionag/yet-another-cloudwatch-exporter/tags/list?next_page=gAAAAABg1i9UjTgAMlBO-fMYc3TNmgMXmn4Y4uZd6SY_bwY3gYK0NCY6N4QtM4YyRSVJITVNODf9K84aLUDZaVXmsHUfXryTblSGiLFb36Y_TY3Yf5sTBtw%3D&n=50" | grep link
```

**Comment by deitch** [comment]
The distribution spec, specifically the pagination part, is [here](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery). The spec discusses using `last` as a query parameter to indicate the last one sent (i.e. if I asked for 50 and `last=foo`, then send me 50 beginning with the first one after `foo`, in lexical sort order), but doesn't necessarily state how the `Link` header indicates what is next; I assume it relies on the [rfc for the link header](https://datatracker.ietf.org/doc/html/rfc8288), which doesn't explicitly reference `rel="next"` except in an example, but is commonly accepted.

If the `link: ... rel="next"` works across all registries, then I certainly have no issue with a refactor of this to make it work universally.

Open a PR?

**Comment by gabegorelick** [comment]
https://issues.redhat.com/browse/PROJQUAY-498

> In order to comply with the OCI spec, we need to change the tags list API pagination to resume from the `last` tag specified (by name), rather than a `next_page` token.
>
> NOTE: If we find that this is too intensive of a query, this change should not be made, because OCI tooling still makes use of the `Next` header, which we fill in properly

So Quay seems to acknowledge that they're not compliant with the spec, but so far there's been no sign of rolling out a fix.
