### ISSUE TITLE
Clash with old docker_registry gem

### ISSUE THREAD

**Issue by dmitryfleytman** [deitch/docker_registry2#8]
Hi,

There is a name clash with old docker_registry gem used for v1 docker registries and index.docker.io. Both gems define DockerRegistry::Registry class which makes it impossible to use both of them in one program.

Is it a real problem or am I missing something?

Thanks!

**Comment by dmitryfleytman** [comment]
I just posed a pull request that fixes the problem. Please take a look.

**Comment by deitch** [comment]
Thanks! Looking now.

**Comment by deitch** [comment]
Closed in favour of #9
